[project]
name = "dbt-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dagster-webserver>=1.10.18",
    "dagster>=1.10.18",
    "dbt-snowflake==1.7.1",
    "dagster-dbt>=0.26.18",
]
